# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 12:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EdgeLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(max_length=100, validators=[django.core.validators.RegexValidator(message="Vertex label doesn't comply", regex='^[a-zA-Z_$][a-zA-Z_$0-9]*$')])),
                ('description', models.TextField()),
                ('MultipleCardinality', models.BooleanField(default=False, help_text='Edge cardinality [Single cardinality is default]')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, validators=[django.core.validators.RegexValidator(message="Property name doesn't comply", regex='^[a-zA-Z_$][a-zA-Z_$0-9]*$')])),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('Smallint', 'Smallint'), ('Int', 'Int'), ('Bigint', 'Bigint'), ('Varint', 'Varint'), ('Float', 'Float'), ('Double', 'Double'), ('Decimal', 'Decimal'), ('Boolean', 'Boolean'), ('Text', 'Text'), ('Uuid', 'Uuid'), ('Timestamp', 'Timestamp'), ('Duration', 'Duration'), ('Linestring', 'Linestring'), ('Polygon', 'Polygon'), ('Inet', 'Inet'), ('Blob', 'Blob')], default='Text', max_length=10)),
                ('MultipleCardinality', models.BooleanField(default=False, help_text='Property with multiple values [Single cardinality is default]')),
                ('parent_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_properties', to='designer.Property')),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VertexLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(max_length=100, validators=[django.core.validators.RegexValidator(message="Vertex label doesn't comply", regex='^[a-zA-Z_$][a-zA-Z_$0-9]*$')])),
                ('description', models.TextField()),
                ('properties', models.ManyToManyField(blank=True, to='designer.Property')),
            ],
        ),
        migrations.AddField(
            model_name='edgelabel',
            name='properties',
            field=models.ManyToManyField(blank=True, to='designer.Property'),
        ),
    ]
