# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0006_auto_20161003_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edgelabel',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vertexlabel',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
