# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0009_edgeconnection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edgeconnection',
            old_name='fromVertex',
            new_name='from_vertex',
        ),
        migrations.RenameField(
            model_name='edgeconnection',
            old_name='toVertex',
            new_name='to_vertex',
        ),
    ]
