# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 21:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0010_auto_20161003_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edgelabel',
            name='label',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message="Vertex label doesn't comply", regex='^[a-zA-Z_$][a-zA-Z_$0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message="Property name doesn't comply", regex='^[a-zA-Z_$][a-zA-Z_$0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='vertexlabel',
            name='label',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message="Vertex label doesn't comply", regex='^[a-zA-Z_$][a-zA-Z_$0-9]*$')]),
        ),
        migrations.AlterUniqueTogether(
            name='edgelabel',
            unique_together=set([('schema', 'label')]),
        ),
        migrations.AlterUniqueTogether(
            name='property',
            unique_together=set([('schema', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='vertexlabel',
            unique_together=set([('schema', 'label')]),
        ),
    ]
