# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0011_auto_20161003_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='slug',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
