# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0013_auto_20161004_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metaproperty',
            name='parent_property',
        ),
        migrations.AddField(
            model_name='property',
            name='meta_properties',
            field=models.ManyToManyField(blank=True, to='designer.Property'),
        ),
        migrations.DeleteModel(
            name='MetaProperty',
        ),
    ]
